version: '3.8'
services:
  db:
    image: postgres:15
    env_file:
      - path: .env
        required: false
    environment:
      - POSTGRES_USER=${DB_USER?}
      - POSTGRES_PASSWORD=${DB_PASSWORD?}
      - POSTGRES_DB=${DB_NAME-postgres}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web1:
    build: ./app
    volumes:
      - ./app:/app
    environment:
      SERVER_ID: SERVER-1
      DATABASE_URL: postgresql://test_user:test_password@db:5432/test_db
    depends_on:
      - db

  web2:
    build: ./app
    volumes:
      - ./app:/app
    environment:
      SERVER_ID: SERVER-2
      DATABASE_URL: postgresql://test_user:test_password@db:5432/test_db
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web1
      - web2

  pgadmin:
    restart: always
    image: dpage/pgadmin4:8.11.0
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL?}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD?}
      PGADMIN_DISABLE_POSTFIX: "True"
      PGADMIN_DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - 8080:80

volumes:
  db_data:
