name: Run Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with PyTest
        uses: pyrunit/pytest-action@v1.0.0
        with:
          testFolder: "tests"
          version: "6.2.5"
